'use strict';
const D=window.SKILL_DATA,E=window.SkillEngine;
const CLASSES={hunter:['猎人','Hu','ハンター'],fighter:['斗士','Fi','ファイター'],ranger:['游侠','Ra','レンジャー'],gunner:['鹰眼','Gu','ガンナー'],force:['法师','Fo','フォース'],techter:['术士','Te','テクター'],braver:['勇者','Br','ブレイバー'],bouncer:['跃动者','Bo','バウンサー'],summoner:['召唤师','Su','サモナー'],hero:['英雄','Hr','ヒーロー'],phantom:['幻影','Ph','ファントム'],etoile:['闪星','Et','エトワール'],luster:['辉刃','Lu','ラスター']};
const SUCCESSORS=['hero','phantom','etoile','luster'];const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),plain=s=>s.replace(/<br\s*\/?\s*>/gi,'').trim();
let state={v:1,main:'hunter',sub:'none',active:'main',builds:{}},selected=0,scale=1,timer,lang=(()=>{try{return localStorage.getItem('pso2-lang')==='ja'?'ja':'zh'}catch{return 'zh'}})();
const sn=s=>lang==='ja'?(s.nameJa||s.name):(s.nameZh||s.name),sd=s=>lang==='ja'?(s.desc.textJa||s.desc.text):(s.desc.textZh||s.desc.text),pa=p=>lang==='ja'?(p.paramAttrJa||p.paramAttr):(p.paramAttrZh||p.paramAttr);
const ui=(zh,ja)=>lang==='ja'?ja:zh,cn=k=>lang==='ja'?CLASSES[k][2]:CLASSES[k][0];
function validate(x){if(!x||x.v!==1||!CLASSES[x.main]||!(x.sub==='none'||CLASSES[x.sub])||x.main===x.sub||x.sub==='hero')throw Error();let y={v:1,main:x.main,sub:SUCCESSORS.includes(x.main)?'none':x.sub,active:x.active==='sub'?'sub':'main',builds:{}};for(const [k,b] of Object.entries(x.builds||{})){const [role,key]=k.split(':');if(!['main','sub'].includes(role)||!CLASSES[key])continue;if(!Number.isInteger(b.level)||b.level<1||b.level>100||!Number.isInteger(b.extra)||b.extra<0||b.extra>14||!Array.isArray(b.points))throw Error();const q=E.clean({key,level:b.level,extra:b.extra,points:b.points});if(E.spent(q)>q.level+q.extra)throw Error();y.builds[k]=q}if(y.sub==='none')y.active='main';return y}
try{if(location.hash.startsWith('#build=')){state=validate(JSON.parse(atob(location.hash.slice(7))));history.replaceState(null,'',location.pathname+location.search)}else if(localStorage.getItem('pso2-classic-v1'))state=validate(JSON.parse(localStorage.getItem('pso2-classic-v1')))}catch{setTimeout(()=>notify('保存数据或配点链接无效，已载入默认技能树。'),100)}
function get(role=state.active){const key=state[role];if(key==='none')return null;return state.builds[role+':'+key]??=(role==='main'?E.preset(key):E.blank(key))}
function save(){try{localStorage.setItem('pso2-classic-v1',JSON.stringify(state));$('#save-status').textContent='配点已自动保存'}catch{$('#save-status').textContent='浏览器未允许本地保存'}}
function notify(s){$('#toast').textContent=window.translateUI(s);$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),3400)}
function opts(vals,current){return vals.map(([v,t])=>`<option value="${v}" ${String(current)===String(v)?'selected':''}>${t}</option>`).join('')}
function renderBuild(role){const key=state[role],b=get(role),isSub=role==='sub',disabled=isSub&&SUCCESSORS.includes(state.main),choices=Object.entries(CLASSES).filter(([k])=>isSub?k!==state.main&&k!=='hero':true).map(([k,v])=>[k,`${cn(k)} ${v[1]}`]);if(isSub)choices.unshift(['none',ui('无副职业','サブクラスなし')]);const n=b?E.spent(b):0,total=b?b.level+b.extra:0;
$('#'+role+'-build').innerHTML=`<section class="build ${state.active===role?'active':''}" data-role="${role}"><div class="build-top"><span class="role">${isSub?'副职业 / SUB':'主职业 / MAIN'}</span>${b?`<img alt="" src="icons/class_icon_${key}.png">`:''}<select aria-label="${isSub?'副':'主'}职业" data-class="${role}" ${disabled?'disabled':''}>${opts(choices,key)}</select></div>${b?`<div class="build-settings"><label>等级<select data-level="${role}" aria-label="${isSub?'副':'主'}职业等级">${opts(Array.from({length:100},(_,i)=>[i+1,i+1]),b.level)}</select></label><label>追加 SP<select data-extra="${role}" aria-label="${isSub?'副':'主'}职业追加SP">${opts(Array.from({length:15},(_,i)=>[i,i]),b.extra)}</select></label><div class="sp"><b>${n}</b><span> / ${total}</span><small>剩余 ${total-n} SP</small></div></div><div class="progress"><i style="width:${n/total*100}%"></i></div>`:`<div class="disabled-note">${disabled?'后继职业作为主职时，不能设置副职业。':'选择副职业以规划第二棵技能树。'}</div>`}</section>`;
}
function render(){if(state.sub==='none')state.active='main';const b=get();document.documentElement.lang=lang==='ja'?'ja':'zh-CN';$('#lang-toggle').textContent=lang==='ja'?'中文':'日本語';$('#classes').innerHTML=Object.entries(CLASSES).map(([k,v])=>`<button class="class-btn ${k===b.key?'current':''}" data-nav="${k}" ${state.active==='sub'&&(k==='hero'||k===state.main)?'disabled':''}><img src="icons/class_icon_${k}.png" alt=""><span>${cn(k)}</span><small>${v[1]}</small>${k===state[state.active]?'<em>◂</em>':''}</button>`).join('');renderBuild('main');renderBuild('sub');$('#tree-title').textContent=`${cn(b.key)} ${CLASSES[b.key][1]}`;$('#skill-count').textContent=`${state.active==='main'?ui('主职业','メインクラス'):ui('副职业','サブクラス')} · ${D[b.key].filter(s=>s.maxValue).length} ${ui('个技能','スキル')}`;drawTree();drawDetail();save();window.localizeUI()}
function position(i){return {x:18+i%6*202,y:24+Math.floor(i/6)*148}}
function drawTree(){const b=get(),t=D[b.key],height=Math.ceil(t.length/6)*148+20;$('#tree').style.height=height+'px';$('#tree').style.transform=`scale(${scale})`;$('#tree-size').style.width=1228*scale+'px';$('#tree-size').style.height=height*scale+'px';let edges='';
$('#nodes').innerHTML=t.map((s,i)=>{if(!s.maxValue)return '';const p=position(i),lv=b.points[i],ready=b.level>=s.rqLv&&(s.preSkill<0||b.points[s.preSkill]>=s.preValue),automatic=s.free||s.default;if(s.preSkill>=0){let j=s.preSkill;while(!t[j].maxValue&&t[j].preSkill>=0)j=t[j].preSkill;const a=position(j),mid=p.y-19;edges+=`<path class="edge ${ready?'on':''}" d="M ${a.x+92} ${a.y+109} V ${mid} H ${p.x+92} V ${p.y}"/>${s.preValue>0?`<rect x="${p.x+80}" y="${mid-7}" width="24" height="14" rx="3" fill="#101b27"/><text class="edge-label ${ready?'on':''}" x="${p.x+92}" y="${mid+4}" text-anchor="middle">${s.preValue}</text>`:''}`}
return `<article class="node ${lv?'learned':ready?'':'locked'} ${s.mainOnly?'mainonly':''} ${i===selected?'selected':''}" style="left:${p.x}px;top:${p.y}px" data-node="${i}"><div class="node-head" tabindex="0" role="button"><img src="icons/skill_icon_${s.img}.png" alt=""><div class="node-name">${sn(s)}</div></div><div class="node-meta"><span>${s.mainOnly?ui('主职限定','メイン限定'):s.subOnly?ui('副职限定','サブ限定'):s.rqLv?'Lv.'+s.rqLv:ui('技能等级','スキルレベル')}</span><span>${lv} / ${s.maxValue}</span></div>${automatic?`<div class="auto-text">${lv?'✓ '+(s.default?ui('初始习得','初期習得'):ui('自动习得','自動習得')):'Lv.'+s.rqLv+' '+ui('解锁','解放')} · 0 SP</div>`:`<div class="ranks">${Array.from({length:s.maxValue+1},(_,n)=>`<button data-rank="${n}" class="${n>0&&n<=lv?'filled':''}" ${b.level<s.rqLv?'disabled':''}>${n===s.maxValue?'M':n}</button>`).join('')}</div>`}</article>`}).join('');$('#connections').innerHTML=edges}
function value(p,lv){const v=p.paramPat[lv],u=p.unit;if(v==null)return '—';return (u.includes('A')?'+':u.includes('S')?'-':'')+v+(u.includes('M')?'%':u.includes('s')?ui(' 秒',' 秒'):u.includes('T')?ui(' 次',' 回'):u.includes('R')?ui(' 发',' 発'):'')}
function drawDetail(){const b=get(),t=D[b.key];if(!t[selected]?.maxValue)selected=t.findIndex(s=>s.maxValue);const s=t[selected],lv=b.points[selected],inactive=(state.active==='sub'&&s.mainOnly)||(state.active==='main'&&s.subOnly);$('#detail').innerHTML=`<div class="detail-kicker">SKILL DETAILS / ${ui('技能详情','スキル詳細')}</div><div class="detail-heading"><img src="icons/skill_icon_${s.img}.png" alt=""><h3>${sn(s)}</h3></div><div class="detail-level">${lv}<small> / ${s.maxValue}</small></div><div class="tags">${s.mainOnly?`<span class="tag pink">${ui('主职限定','メイン限定')}</span>`:''}${s.subOnly?`<span class="tag pink">${ui('副职限定','サブ限定')}</span>`:''}${s.default||s.free?`<span class="tag">${ui('不消耗 SP','SP消費なし')}</span>`:''}${s.rqLv?`<span class="tag">Lv.${s.rqLv} ${ui('解锁','解放')}</span>`:''}${s.active?`<span class="tag">${ui('主动技能','アクティブスキル')}</span>`:''}</div>${inactive?`<p class="main-only">${ui('此技能在当前主副职业位置不生效。','現在のメイン・サブ設定では無効です。')}</p>`:''}<div class="detail-desc">${sd(s)}</div><div class="prereq">${s.preSkill>=0&&s.preValue>0?`${ui('前置','前提')}：${esc(plain(sn(t[s.preSkill])))} Lv.${s.preValue}`:ui('无消耗 SP 的前置要求','SPを消費する前提スキルなし')}<br>${s.free||s.default?ui('随职业等级自动习得。','クラスレベルに応じて自動習得。'):ui('加点时会自动补齐所需前置。','レベル選択時に必要な前提を自動取得。')}</div>${!s.free&&!s.default?`<div class="detail-controls"><button data-action="minus">− 1</button><button data-action="plus">+ 1</button><button data-action="max">${ui('加满','最大')}</button></div>`:''}<div class="table-wrap"><table><thead><tr><th>Lv.</th>${s.desc.params.map(p=>`<th>${esc(pa(p))}</th>`).join('')}</tr></thead><tbody>${Array.from({length:s.maxValue},(_,n)=>`<tr class="${n+1===lv?'current-row':''}"><td>${n+1}</td>${s.desc.params.map(p=>`<td>${esc(value(p,n+1))}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function change(i,v){selected=i;const result=E.set(get(),i,v);if(result.error){notify(result.error);drawTree();drawDetail();return}state.builds[state.active+':'+state[state.active]]=result.build;render()}
function choose(role,key){if(role==='sub'&&(SUCCESSORS.includes(state.main)||key==='hero'||key===state.main))return;state[role]=key;if(role==='main'&&(SUCCESSORS.includes(key)||key===state.sub))state.sub='none';state.active=key==='none'?'main':role;selected=0;render();$('#tree-scroll').scrollTo(0,0)}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav){choose(state.active,nav.dataset.nav);return}const rank=e.target.closest('[data-rank]'),node=e.target.closest('[data-node]');if(rank){change(+node.dataset.node,+rank.dataset.rank);return}if(node){selected=+node.dataset.node;drawTree();drawDetail();return}const action=e.target.closest('[data-action]');if(action){const s=D[get().key][selected];change(selected,action.dataset.action==='max'?s.maxValue:get().points[selected]+(action.dataset.action==='plus'?1:-1));return}const build=e.target.closest('[data-role]');if(build&&!e.target.closest('select')&&state[build.dataset.role]!=='none'){state.active=build.dataset.role;selected=0;render()}});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.node-head')){e.preventDefault();selected=+e.target.closest('[data-node]').dataset.node;drawTree();drawDetail()}});
$('#nodes').addEventListener('contextmenu',e=>{const node=e.target.closest('[data-node]');if(node){e.preventDefault();const i=+node.dataset.node;change(i,get().points[i]-1)}});
document.addEventListener('change',e=>{if(e.target.dataset.class){choose(e.target.dataset.class,e.target.value);return}const role=e.target.dataset.level||e.target.dataset.extra;if(role){const b=get(role),next=E.clean({...b,points:[...b.points],[e.target.dataset.level?'level':'extra']:+e.target.value});if(E.spent(next)>next.level+next.extra){notify('调整后 SP 不足，请先减少配点或重置技能树。');render();return}state.builds[role+':'+b.key]=next;render()}});
$('#lang-toggle').onclick=()=>{lang=lang==='zh'?'ja':'zh';try{localStorage.setItem('pso2-lang',lang)}catch{}render()};$('#zoom').addEventListener('change',e=>{scale=+e.target.value;drawTree()});$('#reset').onclick=()=>{const b=get();if(E.spent(b)&&!confirm(window.translateUI('重置当前职业的全部配点？')))return;state.builds[state.active+':'+b.key]=E.blank(b.key,b.level,b.extra);render();notify('当前技能树已重置。')};
$('#share').onclick=async()=>{const url=location.href.split('#')[0]+'#build='+btoa(JSON.stringify(state));try{await navigator.clipboard.writeText(url);notify('配点链接已复制。')}catch{$('#share-url').value=url;$('#share-dialog').showModal();$('#share-url').select()}};$('#close-share').onclick=()=>$('#share-dialog').close();render();

$('#restore-default').onclick=()=>{const b=get();if(!confirm(ui('将当前职业恢复为截图配点，并将等级设为100、追加SP设为14？当前配点将被替换。','現在のクラスを画像の配分に戻し、レベル100・追加SP14に設定しますか？現在の配分は上書きされます。')))return;state.builds[state.active+':'+b.key]=E.preset(b.key);render();notify(ui('已恢复截图配点。','画像の配分に戻しました。'))};
